### ISSUE TITLE
Server closes when trying to connect from client

### ISSUE THREAD

**Issue by ejuarezg** [DeskX11/DeskX#1]
Hi @mrrva 

Whenever I try to connect to the server on my local network using the command `./dxc --ip=192.168.1.166 --port=4431 --compression=15`, I get the following error on the server side:

`zsh: segmentation fault (core dumped)  ./dxs --port=4431`

(I'm running zsh shell by the way.)

When I try to restart the server, I get the following:

```
dxs: server/net.cpp:16: netw::netw(int): Assertion `bind(sock1, own.ptr, size) == 0' failed.
zsh: abort (core dumped)  ./dxs --port=4431
```
I don't have much else to give you to debug.

Thanks!

**Comment by mrrva** [comment]
Hi! The last error related to the bind function was caused by the fact that after the first time the operating system occupied port 4431 and the program did not have time to release it due to an error. To fix it, change the port, for example, to 4432. Regarding the segmentation fault - this is already an error inside the program, does your shell work on the basis of the x-window manager? and can you please tell us your screen resolution? I will search for what reason the error occurred.

**Comment by mrrva** [comment]
Also try to run the program as I said in the previous post with port 4432 and with the parameter --password=123 for example on the server side and on the client side. There may be a problem with the parsing of arguments.

**Comment by ejuarezg** [comment]
Thanks for the quick reply. First, I realized that I was running the server over an SSH session. After logging in to the Plasma (X11) desktop on the server and running `dxs` from a terminal, I now get this error:

```
dxc: client/x11.cpp:11: x11_client::x11_client(headers): Assertion `hdrs.width <= owidth && hdrs.height <= oheight' failed.
zsh: abort (core dumped)  ./dxc --ip=192.168.1.166 --port=4435 --password=123 --compression=15
```

**Comment by mrrva** [comment]
And this error is due to the fact that most likely the screen resolution on your server exceeds the resolution on the computer :) For now, this is a caste and a kind of overflow protection. Later I will add a function to automatically change the server screen resolution to prevent this kind of error. In the meantime, if you want to try the program, you need to change the screen resolution on the server to the equivalent client resolution (or less). For example, you can do it via the console program xrandr. I can throw off the example command if required. Regarding the previous message - now I will fill in a patch so that this does not arise anymore.

**Comment by ejuarezg** [comment]
You are indeed right. I lowered the resolution on the server and it worked. Thanks for the workaround! I look forward to your patch.

**Comment by mrrva** [comment]
https://github.com/DeskX11/DeskX/commit/8180544395d239fc2f8f402b4c018f6030f898ae Changes have been made. Thanks again for noticing the error.
