### ISSUE TITLE
Is this a teamviewer replacement?

### ISSUE THREAD

**Issue by jhjacobs81** [DeskX11/DeskX#2]
I know its for LAN only, but could i think of this as a teamviewer replacement? And does it work on Windows?

**Comment by mrrva** [comment]
In principle, this can be a replacement for teamviewer if you make an encrypted tunnel between computers, but I don't see much point in doing this. Later I will add, of course, the traffic encryption option in order to securely connect via the internet. Windows - at this stage there is no support, later it will appear (on Macos too).

**Comment by mrrva** [comment]
What are the new terms, what do you mean?

**Comment by jhjacobs81** [comment]
I havent read them yet :) but i hear people complaining about the ToS of Teamviewer and looking for other alternatives :)
