### ISSUE TITLE
 ./dxs --cmd=all --port=4431 --password=secret >> not work

### ISSUE THREAD

**Issue by OmidZamani** [DeskX11/DeskX#9]
o.zamani@RD-ZAMANI-KUB:~/DeskX$ ./dxs --cmd=all --port=4431 --password=secret
**terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)**

this export and not work

**Comment by mrrva** [comment]
Thank you for reporting the bug. I'll take a look.

**Comment by mrrva** [comment]
I found out that this error occurs when you try to run the program without display and xauth arguments. Of course, this should not be so, and in the next few hours I will fix it. But even if this error did not exist, remote control would still not start for you, since these arguments are empty. Thanks for your feedback anyway :)

**Comment by mrrva** [comment]
https://github.com/DeskX11/DeskX/commit/0f23e9fbc8744b997d5e50f5e5ddacc68fd0c9f0
